INSERT INTO USER_DATA (USER_ID, NAME, EMAIL,PASSWORD) VALUES (100, 'maciek','maciej.olszewski01@gmail.com', '$2a$10$UK2i70b6U7p.QSf1QTckjuGOO1i/KjZgscPZsHKkjjQY0fJHIQVjy');
INSERT INTO ORGANIZATION (ORGANIZATION_ID,NAME,INVITATION_HASH) VALUES (100,'ncdc','jakajakak');
INSERT INTO ORGANIZATION_USERS (ORGANIZATION_ID,USER_ID) VALUES (100, 100);